
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Fri Oct 24 08:27:50 CET 2013
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int BREAK = 10;
  public static final int CLASS = 39;
  public static final int ELSE = 6;
  public static final int FINAL = 40;
  public static final int IF = 5;
  public static final int NEW = 41;
  public static final int PRINT = 8;
  public static final int READ = 9;
  public static final int RETURN = 11;
  public static final int VOID = 4;
  public static final int WHILE = 7;
  public static final int EXTENDS = 42;
  public static final int PROG = 2;
  public static final int CONST = 3;
  public static final int PLUS = 13;
  public static final int MINUS = 14;
  public static final int TIMES = 15;
  public static final int DIV = 16;
  public static final int MOD = 17;
  public static final int ISEQUAL = 18;
  public static final int ISNOTEQUAL = 19;
  public static final int ISGREATER = 20;
  public static final int ISGREATEREQ = 21;
  public static final int ISLESS = 22;
  public static final int ISLESSEQ = 23;
  public static final int EQUAL = 24;
  public static final int INCREMENT = 25;
  public static final int DECREMENT = 26;
  public static final int SEMI = 34;
  public static final int COMMA = 33;
  public static final int DOT = 35;
  public static final int LPAREN = 31;
  public static final int RPAREN = 32;
  public static final int LSQUARE = 30;
  public static final int RSQUARE = 29;
  public static final int LBRACE = 27;
  public static final int RBRACE = 28;
  public static final int NUMBER = 36;
  public static final int IDENT = 38;
  public static final int CHARCONST = 37;
  public static final int EOF = 0;
  public static final int error = 1;
}

