
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Thu Jul 30 14:16:30 CEST 2015
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int STRING_LITERAL = 44;
  public static final int INCREMENT = 30;
  public static final int CONST = 3;
  public static final int SEMI = 40;
  public static final int LPAREN = 36;
  public static final int ISLESS = 25;
  public static final int MINUS = 17;
  public static final int DECREMENT = 31;
  public static final int RPAREN = 37;
  public static final int AND = 28;
  public static final int ISLESSEQ = 26;
  public static final int OR = 27;
  public static final int COMMA = 39;
  public static final int CLASS = 6;
  public static final int DIV = 19;
  public static final int PLUS = 16;
  public static final int IF = 9;
  public static final int DOT = 38;
  public static final int ABSTRACT = 5;
  public static final int EOF = 0;
  public static final int RETURN = 15;
  public static final int EQUAL = 29;
  public static final int NEW = 8;
  public static final int error = 1;
  public static final int ISEQUAL = 21;
  public static final int BOOLVAL = 42;
  public static final int NUMBER = 41;
  public static final int MOD = 20;
  public static final int IDENT = 45;
  public static final int BREAK = 14;
  public static final int VOID = 4;
  public static final int TIMES = 18;
  public static final int ISNOTEQUAL = 22;
  public static final int LBRACE = 32;
  public static final int ELSE = 10;
  public static final int LSQUARE = 35;
  public static final int READ = 13;
  public static final int CHARCONST = 43;
  public static final int RSQUARE = 34;
  public static final int WHILE = 11;
  public static final int ISGREATER = 23;
  public static final int RBRACE = 33;
  public static final int EXTENDS = 7;
  public static final int PROG = 2;
  public static final int ISGREATEREQ = 24;
  public static final int PRINT = 12;
}

