
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Fri Apr 25 23:17:29 CEST 2014
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int STRING_LITERAL = 43;
  public static final int INCREMENT = 29;
  public static final int CONST = 3;
  public static final int SEMI = 39;
  public static final int LPAREN = 35;
  public static final int ISLESS = 24;
  public static final int MINUS = 16;
  public static final int DECREMENT = 30;
  public static final int RPAREN = 36;
  public static final int AND = 27;
  public static final int ISLESSEQ = 25;
  public static final int OR = 26;
  public static final int COMMA = 38;
  public static final int CLASS = 5;
  public static final int DIV = 18;
  public static final int PLUS = 15;
  public static final int IF = 8;
  public static final int DOT = 37;
  public static final int EOF = 0;
  public static final int RETURN = 14;
  public static final int EQUAL = 28;
  public static final int NEW = 7;
  public static final int error = 1;
  public static final int ISEQUAL = 20;
  public static final int BOOLVAL = 41;
  public static final int NUMBER = 40;
  public static final int MOD = 19;
  public static final int IDENT = 44;
  public static final int BREAK = 13;
  public static final int VOID = 4;
  public static final int TIMES = 17;
  public static final int ISNOTEQUAL = 21;
  public static final int LBRACE = 31;
  public static final int ELSE = 9;
  public static final int LSQUARE = 34;
  public static final int READ = 12;
  public static final int CHARCONST = 42;
  public static final int RSQUARE = 33;
  public static final int WHILE = 10;
  public static final int ISGREATER = 22;
  public static final int RBRACE = 32;
  public static final int EXTENDS = 6;
  public static final int PROG = 2;
  public static final int ISGREATEREQ = 23;
  public static final int PRINT = 11;
}

